### ISSUE TITLE
Folder Parameter Must Be A Valid Folder

### ISSUE THREAD

**Issue by SomeBoringNerd** [dylwedma11748/JTegraNX#14]
Hi, I was trying the software and got an error while trying to use the Browse for Payload button : 

```
Caused by: java.lang.IllegalArgumentException: Folder parameter must be a valid folder
	at com.sun.glass.ui.CommonDialogs.convertFolder(CommonDialogs.java:239)
	at com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:191)
	at com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1678)
	at javafx.stage.FileChooser.showDialog(FileChooser.java:419)
	at javafx.stage.FileChooser.showOpenDialog(FileChooser.java:354)
	at ui.MainUIController.browseForPayload(MainUIController.java:181)
	... 62 more
```
I have to say, i run the software out of a secondary HDD (after trying, it dont work on my main drive either). The issue happen with Java 11 and 17 (dont even run with Java 8).

I tried this fix https://github.com/dylwedma11748/JTegraNX/issues/10 thinking it would resolve the issue but it didn't. I run a updated version of Mint

Thank for your help, your software look really great

**Comment by SomeBoringNerd** [comment]
While i'm at it, there is also an issue with the Change Bundled Payloads option :
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1862)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1729)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1857)
	... 42 more
Caused by: java.lang.NullPointerException
	at handlers.PayloadHandler.determineUpdates(PayloadHandler.java:112)
	at handlers.PayloadHandler.updatePayloads(PayloadHandler.java:72)
	at ui.MainUIController.changeSetting(MainUIController.java:239)
	... 54 more

```

**Comment by dylwedma11748** [comment]
As for the "Change Bundled Payloads" option, for awhile it was working but because of GitHub not allowing the amount of requests that JTegraNX is sending, all the GitHub connectivity will only work for a bit of time until it just stops working altogether, but it will work again after a brief amount of time. I'm thinking that the way to fix that is to cache the results and say like get fresh copies of the data after a certain time, like an hour or so. I'm still figuring out that one.

As for your external drive situation, can you show me what your main config file looks like?

**Comment by SomeBoringNerd** [comment]
it ended up randomly working again, my config is that one : 

```
[SETTINGS]
savedFolderPath=/home/someboringnerd/Documents/JTegraNX/payloads
savedPayloadPath=/home/someboringnerd/Documents/JTegraNX/payloads/hekate_ctcaer_5.8.0.bin
selectedConfig=No configs
lastSelectedBundledPayload=null
autoInject=false
checkJTegraNXUpdates=true
checkPayloadUpdates=true
enableTrayIcon=false
includeFusse=true
includeHekate=true
includeLockpickRCM=true
includeTegraExplorer=true
minimizeToTray=false

[PAYLOAD RELEASE INFO]
fusee=1.3.2
hekate=v5.8.0
lockpickRCM=v1.9.8
tegraExplorer=4.0.1-hotfix2
```

**Comment by dylwedma11748** [comment]
Wait, so it's working now? Might have just been a fluke. I'm gonna look into that.

**Comment by graynk** [comment]
It's not a fluke. 
When `GlobalSettings.savedFolderPath` is `null` you do `chooser.setInitialDirectory(GlobalSettings.STANDARD_MODE_JTEGRANX_PAYLOAD_DIR);` without checking whether it exists and without creating it if not. So this causes the first exception.

Then when the user closes the application, you do `writer.println("savedFolderPath=" + GlobalSettings.savedFolderPath);`, which writes "savedFolderPath=null" to config file.

Then on the subsequent application start you do 
```Java
if (line.contains("savedFolderPath")) {
    GlobalSettings.savedFolderPath = line.substring(line.indexOf("=") + 1);
}
```
which parses "null" as a String value, and then passes that "null" to the `chooser.setInitialDirectory()`, which causes the same exception.

**Comment by dylwedma11748** [comment]
I'm still trying to figure out what's best to do here, I don't want to keep having to make multiple re-releases of 1.6.9, the 1.7 update is nowhere near ready.

**Comment by ciroiriarte** [comment]
> [SETTINGS]
> savedFolderPath=/home/someboringnerd/Documents/JTegraNX/payloads
> savedPayloadPath=/home/someboringnerd/Documents/JTegraNX/payloads/hekate_ctcaer_5.8.0.bin
> selectedConfig=No configs
> lastSelectedBundledPayload=null
> autoInject=false
> checkJTegraNXUpdates=true
> checkPayloadUpdates=true
> enableTrayIcon=false
> includeFusse=true
> includeHekate=true
> includeLockpickRCM=true
> includeTegraExplorer=true
> minimizeToTray=false

What's the full path for that file?

**Comment by SomeBoringNerd** [comment]
Heya, I dont remember what I did to fix it, nor what was broken to begin with. I should probably close this issue as it did not helped in any way to fix it
