### ISSUE TITLE
Launching fails when prepareGPTRestore() fails on startup

### ISSUE THREAD

**Issue by gmonteir** [dylwedma11748/JTegraNX#4]
Getting the following error when I try to run the jar:

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because "payload" is null
        at handlers.PayloadHandler.prepareGPTRestore(PayloadHandler.java:559)
        at ui.fx.JTegraNX.main(JTegraNX.java:204)
        at main.Main.main(Main.java:5)

**Comment by dylwedma11748** [comment]
Are you building it from source or using the release JAR?

**Comment by gmonteir** [comment]
Latest release.

**Comment by gmonteir** [comment]
Unfortunately it won't run at all, standard, portable, or otherwise.

**Comment by dylwedma11748** [comment]
Ok, soon I'm gonna release a hotfix that doesn't attempt to initialize gptrestore until the user selects the menu item.

**Comment by dylwedma11748** [comment]
Ok, JTegraNX v1.6.9-R1 has been released and provides the fix for your issue, if you could test it and report back, that would be great. If it works I'll close this issue.
