### ISSUE TITLE
After recent java update it will no longer load

### ISSUE THREAD

**Issue by aihooo444** [dylwedma11748/JTegraNX#8]
Here is the log of what is happening 

F:\Games\Switch\Launcher and Games>java -jar JTegraNX.jar
Nov 04, 2021 10:03:52 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 16 by JavaFX runtime of version 8.0.311
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at git.GitHandler.generateLatestRelease(GitHandler.java:57)
        at handlers.PayloadHandler.updatePayloads(PayloadHandler.java:65)
        at ui.fx.JTegraNX.start(JTegraNX.java:88)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        ... 1 more

**Comment by dylwedma11748** [comment]
This issue along with #7 are happening because GitHandler can't find the strings it's looking for, I've got a fix made for it but JTegraNX v1.7 is not ready for release yet. For now just disable auto-updating in the config file to get past this.

**Comment by eks28** [comment]
How do I fix in mac catalina I launch it select standard mode and it closes

I cant find config to try disable auto update to see if would work

Where is config?

**Comment by dylwedma11748** [comment]
The config file gets created after JTegraNX is closed normally using the X, if this doesn't happen, it doesn't get created or updated. You'll have to create a new file and put this in it.

[SETTINGS]
savedFolderPath=null
savedPayloadPath=
selectedConfig=No configs
lastSelectedBundledPayload=
autoInject=false
checkJTegraNXUpdates=false
checkPayloadUpdates=false
enableTrayIcon=false
includeFussePrimary=false
includeHekate=false
includeLockpickRCM=false
includeTegraExplorer=false
minimizeToTray=false

Save it as "JTegraNX.ini" in the same directory as the JAR file.
