### ISSUE TITLE
Crashes on macOS Monterey 12.0.1

### ISSUE THREAD

**Issue by pedrochamberlain** [dylwedma11748/JTegraNX#9]
```cmd
$ java -jar JTegraNX.jar -cml
Exception in thread "main" java.lang.NullPointerException
	at handlers.PayloadHandler.prepareGPTRestore(PayloadHandler.java:559)
	at ui.fx.JTegraNX.main(JTegraNX.java:180)
	at main.Main.main(Main.java:5)
```

Java is updated.

**Comment by dylwedma11748** [comment]
I thought I fixed this issue already, but it looks like it's still happening in command line mode, I'll fix it for v1.7.
